name: Test build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-deploy:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: npm install
        run: npm install
      - name: Test build website
        run: npm run build
